name: Maven Package

on:
  release:
    types: [created]

jobs:
  build-and-attach:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      releases: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Get Maven coordinates
        id: maven-coords
        run: |
          GROUP_ID=$(mvn help:evaluate -Dexpression=project.groupId -q -DforceStdout)
          ARTIFACT_ID=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "coordinates=$GROUP_ID:$ARTIFACT_ID:$VERSION" >> $GITHUB_OUTPUT

      - name: Upload artifact to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target/*.jar
          asset_name: ${{ steps.maven-coords.outputs.artifact_id }}-${{ steps.maven-coords.outputs.version }}.jar
          asset_content_type: application/java-archive

      - name: Create release comment with Maven coordinates
        run: |
          curl -X POST \
            -H "Authorization: token ${{ github.token }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}/comments \
            -d '{"body":"Maven coordinates: `${{ steps.maven-coords.outputs.coordinates }}`\n\nAdd to your project with:\n```xml\n<dependency>\n  <groupId>${{ steps.maven-coords.outputs.group_id }}</groupId>\n  <artifactId>${{ steps.maven-coords.outputs.artifact_id }}</artifactId>\n  <version>${{ steps.maven-coords.outputs.version }}</version>\n</dependency>\n```"}'